inf = input('Digite algo: ')
print('Informações')
print('Tipo primitivo é:', type(inf))
print('Só tem espaços:', inf.isspace())
print('Numérico:', inf.isnumeric())
print('Alfabético:', inf.isalpha())
print('Alfanumérico:', inf.isalnum())
print('Maiúsculas:', inf.isupper())
print('Minúsculas:', inf.islower())
print('Capitalizada:', inf.istitle())
