frase = str(input('Digite seu nome completo: ')).strip()
ma = frase.upper()
mi = frase.lower()
tl = len(frase) - frase.count(' ')
lpn = frase.find(' ')
lista = frase.split()
print(ma)
print(mi)
print(tl)
print(lpn)
print(lista[0])
